production: &production
  url: <%= ENV.fetch('REDIS_HOST', 'redis://localhost:6379/0') %>
  driver: hiredis

staging: &staging
  url: <%= ENV.fetch('REDIS_HOST', 'redis://localhost:6379/0') %>
  driver: hiredis

development: &development
  url: <%= ENV.fetch('REDIS_HOST', 'redis://localhost:6379/0') %>
  driver: hiredis

test: &test
  url: <%= ENV.fetch('REDIS_HOST', 'redis://localhost:6379/1') %>
  driver: hiredis
